# permissions for end users to edit hyperqueues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hyperqueue-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hyperqueue-operator
    app.kubernetes.io/part-of: hyperqueue-operator
    app.kubernetes.io/managed-by: kustomize
  name: hyperqueue-editor-role
rules:
- apiGroups:
  - flux-framework.org
  resources:
  - hyperqueues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux-framework.org
  resources:
  - hyperqueues/status
  verbs:
  - get
