apiVersion: flux-framework.org/v1alpha1
kind: Hyperqueue
metadata:
  labels:
    app.kubernetes.io/name: hyperqueue
    app.kubernetes.io/instance: hyperqueue-sample
    app.kubernetes.io/part-of: hyperqueue-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hyperqueue-operator
  name: hyperqueue-sample
spec:
  # TODO(user): Add fields here
