kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: hyperqueue-operator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard-rwx
  resources:
    requests:
      storage: 1Ti